version: "3.3"
services:
  database:
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes: 
      - ./data/postgres:/var/lib/postgresql/data

  chat-backend:
    build:
      dockerfile: ./docker/backend/Dockerfile
      context: .
    env_file: .env
    networks:
      - default
    depends_on:
      - database
    ports:
      - 8000:8000
      - 8001:8001

  chat-frontend:
    build:
      dockerfile: ./docker/frontend/Dockerfile
      context: .
    networks:
      - default
    ports:
      - 3000:3000
    volumes:
      - '.:/app'
      - '/app/node_modules'
    command: npm start
    tty: true
    stdin_open: true