name: GolangCI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go get -u golang.org/x/lint/golint

      - name: Run build
        run: go build ./cmd/main.go

      - name: Run vet & lint
        run: |
          go vet .
          golint .